"""In-memory session store for the Nexus server.

Holds the message history and context for each active session.
Not persisted to disk — sessions are lost when the server restarts.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from threading import Lock

from ..agent.llm import ChatMessage


@dataclass
class Session:
    """Represents an active chat session.

    Attributes:
        id: Unique identifier (hex UUID) generated by ``SessionStore.create``.
        history: Ordered list of messages exchanged in this session.
        context: Optional context injected into the turn (e.g. vault card content).
    """

    id: str
    history: list[ChatMessage] = field(default_factory=list)
    context: str | None = None


class SessionStore:
    """Thread-safe in-memory session repository.

    All reads and writes are protected by a Lock to ensure consistency when
    multiple requests access the same session concurrently (e.g. the event SSE
    stream running in parallel with POST /chat).
    """

    def __init__(self) -> None:
        self._lock = Lock()
        self._sessions: dict[str, Session] = {}

    def create(self, context: str | None = None) -> Session:
        """Create a new session with an auto-generated ID.

        Args:
            context: Optional initial context for the first turn.

        Returns:
            Newly created session, already registered in the store.
        """
        sid = uuid.uuid4().hex
        with self._lock:
            s = Session(id=sid, context=context)
            self._sessions[sid] = s
            return s

    def get_or_create(self, session_id: str | None, context: str | None = None) -> Session:
        """Return the existing session or create a new one with the given ID.

        Allows the client to pre-generate an ID (``pendingSessionId``) before
        the first POST — ensuring the event SSE stream is open before the turn
        begins so no events are missed.

        Args:
            session_id: Desired ID; None generates a new one automatically.
            context: Applied only if the session is new or ``context`` is still None.

        Returns:
            Session for the given ID, created if necessary.
        """
        if session_id is None:
            return self.create(context=context)
        with self._lock:
            existing = self._sessions.get(session_id)
            if existing is not None:
                if existing.context is None and context is not None:
                    existing.context = context
                return existing
            s = Session(id=session_id, context=context)
            self._sessions[session_id] = s
            return s

    def replace_history(self, session_id: str, history: list[ChatMessage]) -> None:
        """Replace the full history of a session at the end of each turn.

        Silent if ``session_id`` does not exist (the session may have expired
        or never been created due to a very early error).
        """
        with self._lock:
            if session_id in self._sessions:
                self._sessions[session_id].history = history

    def reset(self, session_id: str) -> None:
        """Clear a session's history without removing it from the store."""
        with self._lock:
            if session_id in self._sessions:
                self._sessions[session_id].history = []
