"""generate_image tool — text-to-image and image-edit via OpenAI / Gemini.

The tool resolves API keys from the existing provider configs ("openai"
and "google-gemini") using the same precedence the LLM provider registry
uses (``credential_ref`` → ``use_inline_key`` → ``api_key_env``). It
calls the matching client in :mod:`nexus.agent.image_gen`, persists the
generated bytes under ``assets/generated/`` in the vault, and returns a
markdown ``![]()`` snippet the agent can paste straight into its reply
— which the UI's ``MarkdownView`` renders inline thanks to the
``vault://`` → ``/vault/raw`` rewrite.

Same API key, no extra org verification required for either provider.
"""

from __future__ import annotations

import json
import logging
import os
import re
import unicodedata
from datetime import datetime
from typing import Any

from ..agent.llm import ToolSpec

log = logging.getLogger(__name__)


GENERATE_IMAGE_TOOL = ToolSpec(
    name="generate_image",
    description=(
        "Generate or edit an image using a configured image-gen model "
        "(OpenAI gpt-image-1 or Gemini gemini-2.5-flash-image, aka "
        "'nano banana'). Reuses the OPENAI_API_KEY / GEMINI_API_KEY "
        "the user already configured; no separate billing tier needed. "
        "Saves the result to the vault under assets/generated/ and "
        "returns a markdown image snippet the assistant can paste into "
        "its reply — the UI renders it inline. To EDIT an existing "
        "image, pass `reference_image` as a vault path."
    ),
    parameters={
        "type": "object",
        "properties": {
            "prompt": {
                "type": "string",
                "description": "What the image should depict (or how to edit it).",
            },
            "provider": {
                "type": "string",
                "enum": ["openai", "gemini"],
                "description": "Which image-gen provider to use. Default: 'openai'.",
            },
            "model": {
                "type": "string",
                "description": (
                    "Model id override. Defaults: 'gpt-image-1' for openai, "
                    "'gemini-2.5-flash-image' for gemini."
                ),
            },
            "size": {
                "type": "string",
                "description": (
                    "Output size for OpenAI ('1024x1024' | '1536x1024' | "
                    "'1024x1536'). Ignored by Gemini."
                ),
            },
            "n": {
                "type": "integer",
                "minimum": 1,
                "maximum": 4,
                "description": "Number of images to generate. Default: 1.",
            },
            "reference_image": {
                "type": "string",
                "description": (
                    "Optional vault path to a reference image. When set, "
                    "the tool runs in EDIT mode (OpenAI /v1/images/edits "
                    "or Gemini inline_data part) and the prompt drives the "
                    "modification."
                ),
            },
            "save_path": {
                "type": "string",
                "description": (
                    "Optional vault path override for the first image. "
                    "Subsequent images get a numeric suffix. Defaults to "
                    "'assets/generated/<date>-<slug>-<i>.png'."
                ),
            },
        },
        "required": ["prompt"],
    },
)


_SLUG_BAD = re.compile(r"[^a-z0-9]+")


def _slugify(text: str, *, max_len: int = 40) -> str:
    norm = unicodedata.normalize("NFKD", text)
    ascii_only = norm.encode("ascii", "ignore").decode("ascii").lower()
    slug = _SLUG_BAD.sub("-", ascii_only).strip("-")
    return (slug or "image")[:max_len].rstrip("-") or "image"


def _resolve_api_key(provider: str) -> tuple[str, str | None]:
    """Find the API key for the given provider using the same precedence as
    :func:`nexus.agent.registry.build_registry`.

    Returns ``(api_key, error_message)``. ``error_message`` is non-None
    when the key couldn't be resolved.
    """
    from ..config_file import load as load_config
    from .. import secrets as _secrets

    cfg = load_config()
    provider_id = "openai" if provider == "openai" else "google-gemini"
    pcfg = cfg.providers.get(provider_id)
    if pcfg is None:
        return "", (
            f"provider {provider_id!r} is not configured; run the provider "
            "wizard to add it"
        )

    cred_ref = getattr(pcfg, "credential_ref", None)
    if cred_ref:
        key = _secrets.resolve(cred_ref) or ""
        if not key:
            return "", f"credential {cred_ref!r} for {provider_id} not found"
        return key, None
    if getattr(pcfg, "use_inline_key", False):
        key = _secrets.get(provider_id) or ""
        if not key:
            return "", f"inline key for {provider_id} not present in secrets"
        return key, None
    env_var = getattr(pcfg, "api_key_env", "")
    if env_var:
        key = os.environ.get(env_var, "")
        if not key:
            return "", f"environment variable {env_var} is not set"
        return key, None
    return "", f"no auth configured for provider {provider_id!r}"


def _ext_for_mime(mime: str) -> str:
    return {
        "image/png": ".png",
        "image/jpeg": ".jpg",
        "image/jpg": ".jpg",
        "image/webp": ".webp",
    }.get(mime, ".png")


def _build_save_paths(
    *, prompt: str, count: int, override: str | None, ext: str
) -> list[str]:
    """Return ``count`` distinct vault-relative paths for the generated images."""
    if override:
        base, dot, suffix = override.rpartition(".")
        if not dot:
            base, suffix = override, ext.lstrip(".")
        if count == 1:
            return [f"{base}.{suffix}"]
        return [f"{base}-{i + 1}.{suffix}" for i in range(count)]
    today = datetime.now().strftime("%Y-%m-%d")
    slug = _slugify(prompt)
    return [
        f"assets/generated/{today}-{slug}-{i + 1}{ext}"
        for i in range(count)
    ]


async def handle_image_gen_tool(args: dict[str, Any]) -> str:
    """Dispatcher for ``generate_image`` tool invocations."""
    prompt = (args.get("prompt") or "").strip()
    if not prompt:
        return json.dumps({"ok": False, "error": "`prompt` is required"})

    provider = (args.get("provider") or "openai").strip().lower()
    if provider not in {"openai", "gemini"}:
        return json.dumps(
            {"ok": False, "error": f"unknown provider {provider!r}"}
        )

    n_raw = args.get("n", 1)
    try:
        n = max(1, min(4, int(n_raw)))
    except (TypeError, ValueError):
        n = 1

    api_key, key_err = _resolve_api_key(provider)
    if key_err:
        return json.dumps({"ok": False, "error": key_err})

    # Optional reference image for the edit flow.
    reference_image: bytes | None = None
    reference_mime = "image/png"
    ref_path = (args.get("reference_image") or "").strip()
    if ref_path:
        from .. import multimodal

        try:
            reference_image = multimodal.read_vault_bytes(ref_path)
        except FileNotFoundError as exc:
            return json.dumps(
                {"ok": False, "error": f"reference_image: {exc}"}
            )
        reference_mime = multimodal.sniff_mime(ref_path)

    from ..agent import image_gen

    try:
        if provider == "openai":
            model = args.get("model") or image_gen.DEFAULT_OPENAI_MODEL
            size = args.get("size") or "1024x1024"
            data_list = await image_gen.openai_image(
                api_key,
                prompt,
                model=model,
                size=size,
                n=n,
                reference_image=reference_image,
                reference_mime=reference_mime,
            )
        else:
            model = args.get("model") or image_gen.DEFAULT_GEMINI_MODEL
            data_list = await image_gen.gemini_image(
                api_key,
                prompt,
                model=model,
                n=n,
                reference_image=reference_image,
                reference_mime=reference_mime,
            )
    except Exception as exc:  # noqa: BLE001 — surface upstream + transport errors
        log.warning("generate_image: upstream call failed", exc_info=True)
        return json.dumps({"ok": False, "error": str(exc)})

    if not data_list:
        return json.dumps(
            {"ok": False, "error": "image-gen returned no images"}
        )

    # Persist each image to the vault. We default to PNG; OpenAI's
    # gpt-image-1 returns PNG by default, Gemini returns PNG. If the user
    # asked for a different output format via `save_path`, honour it.
    from .. import vault as _vault

    paths = _build_save_paths(
        prompt=prompt,
        count=len(data_list),
        override=args.get("save_path"),
        ext=".png",
    )

    saved: list[str] = []
    for path, data in zip(paths, data_list):
        try:
            _vault.write_file_bytes(path, data)
        except Exception as exc:  # noqa: BLE001
            log.warning("generate_image: vault write failed for %s", path, exc_info=True)
            return json.dumps(
                {"ok": False, "error": f"vault write failed for {path}: {exc}"}
            )
        saved.append(path)

    # Build the markdown the agent should paste back into its reply. One
    # `![alt](vault://...)` per image; MarkdownView rewrites the URL to
    # /vault/raw at render time.
    snippet_lines = [f"![{prompt[:80]}](vault://{p})" for p in saved]
    markdown = "\n".join(snippet_lines)

    return json.dumps(
        {
            "ok": True,
            "provider": provider,
            "model": model,
            "paths": saved,
            "markdown": markdown,
        }
    )
